# --- BUILD STAGE ---
FROM golang:1.25-alpine AS build_admin
ENV CGO_ENABLED=0

ARG BUILD_REF
WORKDIR /app

# 1. Dependency Caching: Copy go.mod and go.sum first.
COPY go.mod go.sum ./
RUN go mod download

# 2. Source Code Copy: Copy the rest of the source code.
COPY . .

# Build the binary from its specific directory.
WORKDIR /app/api/tooling/admin

# 3. Binary Optimization: Use -s and -w ldflags to strip debug symbols and DWARF tables.
RUN go build -ldflags "-s -w -X main.build=${BUILD_REF}" -o /bin/admin

# --- RUNTIME STAGE ---
# Use the minimal Alpine image for the final production container.
FROM alpine:3.22
ARG BUILD_DATE
ARG BUILD_REF

# 4. Security: Create a dedicated non-root user and group ('admin') with ID 1000.
RUN addgroup -g 1000 -S admin && \
    adduser -u 1000 -h /app -G admin -S admin

WORKDIR /app

# 5. Copy Binary: Copy ONLY the compiled, stripped binary from the build stage.
COPY --from=build_admin --chown=admin:admin /bin/admin /app/admin

# Ensure both binaries are executable
RUN chmod +x /app/admin

# 7. Switch User: Run the container and the application as the non-root user.
USER admin

# 8. Entrypoint: The primary service binary to run on container startup.
CMD ["/app/admin"]

# OCI Labels (Best practice for image metadata)
LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="admin" \
      org.opencontainers.image.authors="hein<heindaemon@gmail.com>" \
      org.opencontainers.image.source="https://github.com/h2a26/go-firstcup/tree/master/a/services/admin" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="summer scent"