services:
  database:
    image: postgres:alpine
    container_name: database
    ports: ["5432:5432"]
    env_file:
      - ../../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - sales-network

  admin:
    build:
      context: ../..
      dockerfile: zarf/docker/dockerfile.admin
    image: admin-service:local
    container_name: admin
    command: ["./admin", "migrate-seed"]
    env_file:
      - ../../.env
    networks:
      - sales-network
    depends_on:
      database:
        condition: service_healthy

  auth:
    build:
      context: ../..
      dockerfile: zarf/docker/dockerfile.auth
    image: auth-service:local
    container_name: auth
    ports: ["6000:6000", "6010:6010"]
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:6000/v1/liveness || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 2
    networks:
      - sales-network
    depends_on:
      admin:
        condition: service_started
      logstash:
        condition: service_healthy

  sales:
    build:
      context: ../..
      dockerfile: zarf/docker/dockerfile.sales
    image: sales-service:local
    container_name: sales
    ports: ["3000:3000", "3010:3010"]
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/v1/liveness || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 2
    networks:
      - sales-network
    depends_on:
      admin:
        condition: service_started
      logstash:
        condition: service_healthy

  metrics:
    build:
      context: ../..
      dockerfile: zarf/docker/dockerfile.metrics
    image: metrics-service:local
    container_name: metrics
    ports: ["4000:4000", "4010:4010", "4020:4020"]
    env_file:
      - ../../.env
    networks:
      - sales-network
    depends_on:
      - sales

  prometheus:
    image: prom/prometheus:v3.7.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../../zarf/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - sales-network
    depends_on:
      - metrics

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    ports:
      - "9091:3000"
    env_file:
      - ../../.env
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - sales-network
    depends_on:
      - prometheus  # needs to add Prometheus datasource, Prometheus server URL = http://prometheus:9090
      - tempo       # needs to add Tempo, Tempo server URL = http://tempo:3200

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "9411:9411"   # Zipkin
      - "14250:14250" # Jaegerc
    volumes:
      - ../../zarf/tempo/tempo.yaml:/etc/tempo/tempo.yaml
    networks:
      - sales-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - sales-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.4
    container_name: logstash
    volumes:
      - ../../zarf/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    environment:
      - "xpack.monitoring.enabled=false"
    networks:
      - sales-network
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - sales-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5601/api/status" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: sales_postgres_data
  grafana-storage:
    driver: local

networks:
  sales-network:
    driver: bridge